### PR TITLE
Remove old Tours - Orthophotos 2008

### PR DESCRIPTION
**Pull request by Cyrille37**

### CODE REVIEW

**Comment by tyrasd** [comment]
You are sure this imagery is completely obsolete now? Sometimes even old imagery can be of help, for example thanks to different lighting in areas that are shaded in the newer one.

**Comment by Cyrille37** [comment]
not shure ...
It was to make less layer in ID ;-)

**Comment by Cyrille37** [comment]
I will check. For waiting, I close the pull request.

Thanks a lot.
Cheers

**Comment by Cyrille37** [comment]
Hi,
Friends confirm me that the "sources/europe/Tours-Orthophotos2008-2010.json" is the same as "sources/europe/Tours-Orthophotos2008.json" with 2010 add-on (more cities).

So it's ok to remove this file "sources/europe/Tours-Orthophotos2008.json".

Thanks

**Pull request merged**
