### PR TITLE
Add AGIV Imagery (Flanders and Brussels)

### PR DESCRIPTION
**Pull request by sanderd17**
This commit should add AGIV imagery (See https://github.com/openstreetmap/iD/issues/2846 for original ticket)

### CODE REVIEW

**Comment by tyrasd** [comment]
merged as https://github.com/osmlab/editor-imagery-index/commit/1a8c1d3eac641cde9a79ae924ce8a4ad9fad208b (where I've left out the [changes](https://github.com/sanderd17/editor-imagery-index/commit/788c515bfb388d48b418f187d7fe68c33962ae82) to the makefile you accidentally commited)

**Comment by bhousel** [comment]
You wanted to add "best: true" for this source, right?

**Comment by tyrasd** [comment]
I've added the "*best*" flag in c3f00d6

**Comment by sanderd17** [comment]
The changes to the makefile were accidental, but AFAICS, it shouldn't break any system. While the current Makefile doesn't work on distros that use Python3 as default s.a. Arch Linux. It took me a while to figure out the script only ran on Python2.

Thanks for adding the "best" flag. I thought this was derived from other data.

Now we'll have less issues with users trying to "fix" buildings and streets by aligning them to Bing imagry

**Pull request closed without merging**
