### PR TITLE
Adding Brazilian IBGE sources

### PR DESCRIPTION
**Pull request by nighto**
Adding brazilian IBGE sources, as discussed on issue #71.

### CODE REVIEW

**Comment by pnorman** [comment]
Please provide `license_url` and `attribution` properties if applicable for those sources.

4k lines is exceptionally large - can the geometries not be simplified?

**Comment by nighto** [comment]
Hello Paul,

I converted the [XML already used by JOSM](https://josm.openstreetmap.de/wiki/Maps/Brazil). These XMLs lacks these tags.

I know that for ```license_url```, IBGE states that their data is Public Domain, as per [this message](https://lists.openstreetmap.org/pipermail/talk-br/2009-January/000029.html) on talk-br list. Should I point to this link? More information on this matter on #71 (on @tmpsantos's comment).

As for ```attribution```, PD does not _requires_ attribution, but they _ask_ to tag the changesets with ```source=IBGE```.

**Comment by vgeorge** [comment]
This will be extremely useful for the Brazilian community!

I've added information about the license at the wiki, so we can use it at `license_url`: 

https://wiki.openstreetmap.org/wiki/IBGE_Tile_Layer

This is a simplified polygon for Brazil, based on Geofabrik brazil.poly file:

https://gist.github.com/vgeorge/9325952419f4cf8ffe74

Arlindo, can you add these to the pull request? Or make another one?

**Comment by nighto** [comment]
@vgeorge @pnorman I'm closing this pull request and opening another one with the updated ```license_url```and simplified country polygon.

**Pull request closed without merging**
