### PR TITLE
Czech TMS sources for iD

### PR DESCRIPTION
**Pull request by zbycz**
Via http://wiki.openstreetmap.org/wiki/WikiProject_Czech_Republic/freemap

Thanks for merging or comments.

### CODE REVIEW

**Comment by pnorman** [comment]
Please provide a license_url. Having "iD tiles" in the name is also wrong, the imagery is not from iD.

After fixing this, run both `make` and `make check`

**Comment by zbycz** [comment]
I fixed `license_url` and squashed changes in one commit. 

Should I create another commit with output of `make`? Or does it compile automatically on merge? ('d be cool!)

**Comment by zbycz** [comment]
May i ask - is it ok now? I would be glad if this change could propagate to official iD before my begginers workshop next thursday.
Thanks!

**Comment by tyrasd** [comment]
>  propagate to official iD before next thursday

That might be a bit unrealistic, as iD only updates its imagery data with every new [release](https://github.com/openstreetmap/iD/releases). Sorry. You could instruct the attendants of your workshop to set this imagery as a custom background layer, in the meantime.

**Comment by zbycz** [comment]
Oh, right. Thanks for that info. I knew just, that my translation updates
were included in the order of days, but maybe i was lucky for it was the
release.

**Comment by bhousel** [comment]
Thanks everyone for your patience, looks like iD 1.7.3 is live now on the main openstreetmap.org site and it includes the new imagery sources for Czech Republic.

**Comment by zbycz** [comment]
Thank you very much, you made it before the workshop - thats wonderful!

And works very well too!

PZ.

**Comment by bhousel** [comment]
Hope the workshop is a success!

**Pull request merged**
