### PR TITLE
Added new data source

### PR DESCRIPTION
**Pull request by kolesar-andras**
Four districts of Budapest, Hungary.

### CODE REVIEW

**Comment by pnorman** [comment]
license information?

**Comment by kolesar-andras** [comment]
Interspect permitted to use for OpenStreetMap mapping.

**Comment by pnorman** [comment]
Please add a license_url linking to the permission, then should be okay to merge (with a `make`)

**Comment by pnorman** [comment]
Closing - submitter never added the license information

**Comment by kolesar-andras** [comment]
Added license_url and created a new pull request (#99).

**Pull request closed without merging**
