### PR TITLE
Add Toulouse 2013 and 2015 imageries

### PR DESCRIPTION
**Pull request by fredericbonifas**

### CODE REVIEW

**Comment by pnorman** [comment]
what's the license URL?

**Comment by fredericbonifas** [comment]
Both imageries are ODbL:
- https://data.toulouse-metropole.fr/explore/dataset/orthophotoplan-2015/
- https://data.toulouse-metropole.fr/explore/dataset/orthophotoplan-2013/

**Comment by pnorman** [comment]
Does 2013 have better coverage or resolution than 2015, or when would 2013 be preferred over 2015? What is their maximum resolution, z22 seems high.

**Comment by fredericbonifas** [comment]
2015 would be often preferred over 2013, but this can be useful to see older imagery in order to detect landuse or buildings changes.
Zoom 22 is available for these two layers, see for example:
- http://wms.openstreetmap.fr/tms/1.0.0/toulouse_2015/22/2113960/1531711.png
- http://wms.openstreetmap.fr/tms/1.0.0/toulouse_2013/22/2113960/1531711.png

Thanks for merging the PR!

**Comment by pnorman** [comment]
> Zoom 22 is available for these two layers, see for example:
> 
> http://wms.openstreetmap.fr/tms/1.0.0/toulouse_2015/22/2113960/1531711.png
> http://wms.openstreetmap.fr/tms/1.0.0/toulouse_2013/22/2113960/1531711.png
> Thanks for merging the PR!

The server supplies z22, but this seems in excess of the imagery resolution

**Pull request merged**
