### PR TITLE
added GSI imagery for Japan

### PR DESCRIPTION
**Pull request by pratikyadav**
For https://github.com/osmlab/editor-imagery-index/issues/111

### CODE REVIEW

**Comment by pnorman** [comment]
license_url please

**Comment by pratikyadav** [comment]
http://www.gsi.go.jp/kikakuchousei/kikakuchousei40182.html
@pnorman ^

**Comment by tyrasd** [comment]
and don't forget to commit the actual `source` file!

**Comment by mapconcierge** [comment]
Thanks, @pratikyadav !!
Awesome! :-)

**Comment by tyrasd** [comment]
I noticed that the polygon for this layer is quite coarse, since the layer doesn't actually cover the whole country in high resolution. I saw that there seem to exist more accurate boundary geometries of this layer in https://github.com/mapbox/mapping/issues/120#issuecomment-140753390 ([this map](https://api.mapbox.com/v4/pratikyadav.79cb6a87/page.html?access_token=pk.eyJ1IjoicHJhdGlreWFkYXYiLCJhIjoiMTA2YWUxNjRkNmFmZGQ4YzAxZWFiNDk0NDM1YjE1YjAifQ.4P6N5dNmA_WQXd3BsJvu5w#11/37.6297/140.1083)) – @pratikyadav do you still have the geometry (geojson?) data for this laying around somewhere?

**Comment by pratikyadav** [comment]
@tyrasd http://geojson.io/#id=gist:pratikyadav/4f45fe7b8ecda9a8eef192f6f3c1f4d3&map=6/39.326/135.747

**Comment by tyrasd** [comment]
thanks! :heart:

**Pull request merged**
